language: node_js

env:
  - CXX=g++-4.8

node_js:
  - '10.0.0'
  - '9.11.1'
  - '8.11.1'
  - '5.1'
  - '5.0'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs-1'
  - 'iojs-2'
  - 'iojs-3'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email: false

sudo: false

before_install:
  - $CXX --version
